#!/bin/bash -e

. /etc/os-release

is_fedora=$(echo $ID | grep -oi fedora)


bv=$(buildah --version)
if (( $? != 0 )); then
    echo install buildah 1.19.3 or later
    exit 1
fi

# translate to array of version components
bv="${bv#buildah version }"
bv="${bv% (*}"
bv=(${bv//./ })

maj=${bv[0]}
min=${bv[1]}
patch=${bv[2]}

ok=$(( maj > 1 || ( maj == 1 && min > 19 ) || ( maj == 1 && min == 19 && patch >= 3 ) ))

if (( ! ok )); then 
    echo install buildah 1.19.3 or later
    exit 1
fi

if !(type git-archive-all > /dev/null 2>&1); then
    if [ "$is_fedora" ]; then
        sudo dnf install -y git-archive-all
    else
        echo install git-archive-all
        exit 1
    fi
fi

# docker arch has a diffrent spelling than uname arch
declare -A docker_arch=(
    [x86_64]=amd64
    [aarch64]=arm64
    [s390x]=s390x
)

usage() {
    cat <<EOF

Options:
  --clang-install          build and install an optimized clang compiler binary.
  --clang-build            build an optimized clang compiler binary and keep in the host directory
  --clang-install-prebuilt install prebuilt optimized clang compiler binary.
  --help                   this help snippet
EOF
    exit 1
}

CLANG_CMD="--build-arg CLANG_BUILD=SKIP"
while [ $# -gt 0 ]; do
    case "$1" in
        "--clang-install")
        CLANG_CMD="--build-arg CLANG_BUILD=INSTALL"
            shift 1
            ;;
        "--clang-build")
        CLANG_CMD="--build-arg CLANG_BUILD=BUILD"
            shift 1
            ;;
        "--clang-install-prebuilt")
        CLANG_CMD="--build-arg CLANG_BUILD=INSTALL_PREBUILT"
            shift 1
            ;;
        "--help")
            usage
            ;;
        *)
            usage
            ;;
    esac
done

mkdir -p build/optimized_clang
git-archive-all --prefix="" build/optimized_clang/scylla-archive.tar
buildah bud --platform="linux/${docker_arch[$(arch)]}" --jobs 0 --squash --no-cache --pull -f tools/toolchain/Dockerfile --manifest "$(<tools/toolchain/image)" -v $(readlink -f build/optimized_clang):/optimized_clang:Z ${CLANG_CMD}

echo "Done building $(<tools/toolchain/image). You can now test it, and push with"
echo ""
echo "    podman manifest push --all $(<tools/toolchain/image) docker://$(<tools/toolchain/image)"
